version: '3.8'
services:
  postgres-test:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"